"""add name_en to master lists

Revision ID: a1b2c3d4e5f6
Revises: 7bb10a8ecb79
Create Date: 2026-02-09 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '7bb10a8ecb79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_industries', sa.Column('name_en', sa.String(length=200), nullable=True))
    op.add_column('master_professions', sa.Column('name_en', sa.String(length=200), nullable=True))
    op.add_column('master_sport_achievements', sa.Column('name_en', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_sport_achievements', 'name_en')
    op.drop_column('master_professions', 'name_en')
    op.drop_column('master_industries', 'name_en')
    # ### end Alembic commands ###
