"""a2w phase 1 - users profiles master tables

Revision ID: 5dc05065b04f
Revises: c756768ae27e
Create Date: 2026-02-07 23:39:16.088036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dc05065b04f'
down_revision: Union[str, None] = 'c756768ae27e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_industries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('master_professions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('master_sport_achievements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('aretan_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('industry_id', sa.Uuid(), nullable=True),
    sa.Column('profession_id', sa.Uuid(), nullable=True),
    sa.Column('max_achievement_id', sa.Uuid(), nullable=True),
    sa.Column('sport_description', sa.Text(), nullable=True),
    sa.Column('professional_description', sa.Text(), nullable=True),
    sa.Column('employment_status', sa.String(length=30), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('social_networks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('phone_visible', sa.Boolean(), nullable=False),
    sa.Column('email_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['master_industries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['max_achievement_id'], ['master_sport_achievements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profession_id'], ['master_professions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aretan_profiles_employment_status'), 'aretan_profiles', ['employment_status'], unique=False)
    op.create_index(op.f('ix_aretan_profiles_industry_id'), 'aretan_profiles', ['industry_id'], unique=False)
    op.create_index(op.f('ix_aretan_profiles_profession_id'), 'aretan_profiles', ['profession_id'], unique=False)
    op.create_index(op.f('ix_aretan_profiles_user_id'), 'aretan_profiles', ['user_id'], unique=True)
    op.create_table('contractor_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('industry_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['master_industries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractor_profiles_industry_id'), 'contractor_profiles', ['industry_id'], unique=False)
    op.create_index(op.f('ix_contractor_profiles_user_id'), 'contractor_profiles', ['user_id'], unique=True)
    op.create_table('work_experiences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('aretan_profile_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aretan_profile_id'], ['aretan_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_experiences_aretan_profile_id'), 'work_experiences', ['aretan_profile_id'], unique=False)
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('accepted_terms_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_country'), 'users', ['country'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_country'), table_name='users')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'accepted_terms_at')
    op.drop_column('users', 'country')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'contact_email')
    op.drop_column('users', 'phone')
    op.drop_index(op.f('ix_work_experiences_aretan_profile_id'), table_name='work_experiences')
    op.drop_table('work_experiences')
    op.drop_index(op.f('ix_contractor_profiles_user_id'), table_name='contractor_profiles')
    op.drop_index(op.f('ix_contractor_profiles_industry_id'), table_name='contractor_profiles')
    op.drop_table('contractor_profiles')
    op.drop_index(op.f('ix_aretan_profiles_user_id'), table_name='aretan_profiles')
    op.drop_index(op.f('ix_aretan_profiles_profession_id'), table_name='aretan_profiles')
    op.drop_index(op.f('ix_aretan_profiles_industry_id'), table_name='aretan_profiles')
    op.drop_index(op.f('ix_aretan_profiles_employment_status'), table_name='aretan_profiles')
    op.drop_table('aretan_profiles')
    op.drop_table('master_sport_achievements')
    op.drop_table('master_professions')
    op.drop_table('master_industries')
    # ### end Alembic commands ###
